# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-14 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('productname', models.CharField(max_length=100)),
                ('productclass', models.CharField(max_length=100)),
                ('productcolor', models.CharField(max_length=100)),
                ('productcost', models.IntegerField()),
            ],
        ),
    ]
