# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-14 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0002_auto_20190714_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='State',
            field=models.IntegerField(max_length=100),
        ),
    ]
